title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

aux_links:
  "gae-js on GitHub":
    - "//github.com/mondo-mob/gae-js"

aux_links_new_tab: true
color_scheme: dark
