title: GAE JS
description: Simplify building NodeJS applications on Google App Engine (GAE)
theme: just-the-docs

aux_links:
  "gae-js on GitHub":
    - "//github.com/mondo-mob/gae-js"

aux_links_new_tab: true
color_scheme: dark
